# Configuration ip for redlrm
mip 0.0.0.0
# Port used to receive data from the IP switch
# Data receiving port for the IP switch
sport 52719

# Port used to receive heartbeat from the IP switch
# Heartbeat receiving port for the IP switch or core service
shearbeatport 8888

# Port used to receive data from the core service
# Data receiving port for the core service
# cport 8898

# Port number used to communicate with the core service.
coreport 52719

# Heartbeat port number used to communicate with the core service.
coreheartbeatport 52719

# IP address of the core service.
# Usually set to localhost (127.0.0.1) for local communication.
coreip 192.168.211.130

broadcastip 192.168.211.255

# Port number used to communicate with the switch service.
switchport 6000

# Heartbeat port number used to communicate with the switch service.
switchheartbeatport 50001

# IP address of the switch service.
# Use 127.0.0.1 if the switch runs on the same host.
switchip 127.0.0.1

# Port number used to communicate with the auth service.
authport 48350

# IP address of the auth service.
# Use 127.0.0.1 if the switch runs on the same host.
authip 192.168.110.206

# Auth refresh time, between 5 to 10 minutes.
# Set in seconds."
authrefreshtime 300

# By default redlrm does not run as a daemon. Use 'yes' if you need it.
# Note that redlrm will write a pid file in /var/run/redlrm.pid when daemonized.
daemonize no

# If a pid file is specified, sandtable writes it where specified at startup
# and removes it at exit.
#
# When the server runs non daemonized, no pid file is created if none is
# specified in the configuration. When the server is daemonized, the pid file
# is used even if not specified, defaulting to "/var/run/sandtable.pid".
#
# Creating a pid file is best effort: if sandtable is not able to create it
# nothing bad happens, the server will start and run normally.
#pidfile /var/run/redlrm.pid

# Specify the log file name. Also the empty string can be used to force
# to log on the standard output. Note that if you use standard
# output for logging but daemonize, logs will be sent to /dev/null
#logfile /home/yrb/src/redlrm/redlrm.log

# Set the storage size of the log file. 
# If it exceeds the set size, the file 
# will be named after the current time, 
# and then a new log file will be re-created. 
# If not set, the default size will be 100 MB. in megabytes
logfilesize 100